In [20]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(0,20).reshape(5,4),index=['r1', 'r2','r3', 'r4', 'r5' ], columns=['A', 'B', 'C', 'D']) #if index and columns are not given, it will be assigned with default values
df.to_csv('first.csv')
print(df)
df.head(2) #it will show the first 2 rows of the dataframe

     A   B   C   D
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15
r5  16  17  18  19

    A  B  C  D
r1  0  1  2  3
r2  4  5  6  7

In [ ]:
df.loc['r1'] #this is a dataseries

pandas.Series

In [ ]:
df1 = df.iloc[1:3, :] #this is a dataframe(if there is more than on column or row, it will be a dataframe)
df1

    A  B   C   D
r2  4  5   6   7
r3  8  9  10  11

In [17]:
df1.describe()

              A         B          C          D
count  2.000000  2.000000   2.000000   2.000000
mean   6.000000  7.000000   8.000000   9.000000
std    2.828427  2.828427   2.828427   2.828427
min    4.000000  5.000000   6.000000   7.000000
25%    5.000000  6.000000   7.000000   8.000000
50%    6.000000  7.000000   8.000000   9.000000
75%    7.000000  8.000000   9.000000  10.000000
max    8.000000  9.000000  10.000000  11.000000

In [19]:
#df to array
df.iloc[:, :].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
print(df.isnull())
print(df.isnull().sum())

        A      B      C      D
r1  False  False  False  False
r2  False  False  False  False
r3  False  False  False  False
r4  False  False  False  False
r5  False  False  False  False
A    0
B    0
C    0
D    0
dtype: int64

In [29]:
df[['A', 'B']] #this will show only the columns A and B

     A   B
r1   0   1
r2   4   5
r3   8   9
r4  12  13
r5  16  17

In [30]:
df['A'].unique() #this will show the unique values in column A

array([ 0,  4,  8, 12, 16])